# Generated by Django 4.1 on 2022-11-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='total',
            field=models.CharField(default='50000', max_length=200),
            preserve_default=False,
        ),
    ]
